---
- name: info vm demo
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  pre_tasks:
    - include_vars: vars.yml

  tasks:
    - name: Gather info from standalone ESXi server having datacenter as 'ha-datacenter'
      community.vmware.vmware_datastore_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        datacenter_name: '{{ vcenter_datacenter }}'
        validate_certs: "{{ vcenter_validate_certs }}"  
        #name: DST_720G
        properties:
          - name
          - info.vmfs.ssd
          - capability.vsanSparseSupported
          - overallStatus
      delegate_to: localhost
      register: info      

    - name: print VM info
      ansible.builtin.debug:
        var: info      