---
collections:
  - name: purestorage.flasharray
    version: 1.17.2
  #- name: purestorage.flashblade
  #  version: 1.11.0
  - name: community.vmware
    version: 3.5.0
#  - name: vmware.vmware_rest
#    version: 2.3.1
  - name: community.windows
    version: 1.12.0
  - name: ansible.windows
    version: 1.13.0
  - name: community.general
    version: 6.6.0
  - name: chocolatey.chocolatey
    version: 1.4.0
    
