---
- hosts: localhost
  gather_facts: no

  vars:
    vcenter_hostname: "192.168.15.141"
    vcenter_username: "administrator@vsphere.local"
    vcenter_password: "administrator"
    datacenter: "Datacenter"
    #cluster: "cluster1"
    datastore: "DST_TEST_01"
    clone_folder: "/Staging"
    guest_name: "webserver"
    guest_template: "Windows10Template"
    vmware_host: "192.168.15.143"
    guest_networks:
      - label: "VM Network"
        vlan: "0"

  tasks:
    - name: Create VMware Guest
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: no
        folder: "{{ clone_folder }}"
        datacenter: "{{ datacenter }}"
        esxi_hostname: "{{ vmware_host }}"	 
        datastore: "{{ datastore }}"
        name: "{{ guest_name }}"
        template: "{{ guest_template }}"
        #networks: "{{ guest_networks }}"

