- name: Create users Windows 
  hosts: all
  tasks:
    - name: Ensure user bob is present
      ansible.windows.win_user:
        name: bob
        password: B0bP4ssw0rd
        state: present
        groups:
          - Users

    #- name: Ensure user bob is absent
    #  ansible.windows.win_user:
    #    name: bob
    #    state: absent